SCHEMA = 'content'
MOVIES_IDX= 'movies'

R_PERSON_EXTRACTOR_STATE = 'person_extractor_state'
R_GENRE_EXTRACTOR_STATE = 'genre_extractor_state'
R_MOVIE_EXTRACTOR_STATE = 'movie_extractor_state'

R_ENRICHER_STATE = 'enricher_state'

EXTRACTOR_LOAD_LIMIT = 100
ENRICHER_LOAD_LIMIT = 100

DEFAULT_EXTRACTOR_STATE = '1000-01-01 00:00:00.000000'
DEFAULT_ENRICHER_STATE = 0
